In [1]:
!pip install pandas psycopg2 sqlalchemy

Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.2.3)
Requirement already satisfied: psycopg2 in d:\anaconda\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.39)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [4]:
conn = psycopg2.connect(
    host="localhost",
    database="itunes_db",
    user="postgres",
    password="raksha"
)

print("Connected successfully!")

Connected successfully!

In [4]:
pd.read_sql("SELECT version();", conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\1547237182.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT version();", conn)

                                             version
0  PostgreSQL 18.1 on x86_64-windows, compiled by...

In [5]:
import pandas as pd

customers = pd.read_csv("customer.csv")
artists = pd.read_csv("artist.csv")
albums = pd.read_csv("album.csv")
tracks = pd.read_csv("track.csv")
genre = pd.read_csv("genre.csv")
employees = pd.read_csv("employee.csv")
invoice = pd.read_csv("invoice.csv")
invoice_items = pd.read_csv("invoice_line.csv")
media_types = pd.read_csv("media_type.csv")
playlist = pd.read_csv("playlist.csv")
playlist_track = pd.read_csv("playlist_track.csv")

In [6]:
customers.head()

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [7]:
tracks.head()

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,NaN,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

In [8]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:raksha@localhost:5432/itunes_db")

In [9]:
customers.to_sql("customers", engine, if_exists="replace", index=False)
artists.to_sql("artists", engine, if_exists="replace", index=False)
albums.to_sql("albums", engine, if_exists="replace", index=False)
tracks.to_sql("tracks", engine, if_exists="replace", index=False)
genre.to_sql("genres", engine, if_exists="replace", index=False)
employees.to_sql("employees", engine, if_exists="replace", index=False)
invoice.to_sql("invoices", engine, if_exists="replace", index=False)
invoice_items.to_sql("invoice_items", engine, if_exists="replace", index=False)
media_types.to_sql("media_types", engine, if_exists="replace", index=False)
playlist.to_sql("playlists", engine, if_exists="replace", index=False)
playlist_track.to_sql("playlist_track", engine, if_exists="replace", index=False)

715

In [10]:
pd.read_sql("SELECT * FROM customers LIMIT 5", conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\3500093629.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FROM customers LIMIT 5", conn)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [11]:
pd.read_sql("SELECT * FROM tracks LIMIT 5", conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\1308681743.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FROM tracks LIMIT 5", conn)

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

In [12]:
## Q1 Senior Most Employee Based on Job Title
query = """
SELECT *
FROM employees
ORDER BY levels DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\2356982933.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

,employee_id,last_name,first_name,title,reports_to,levels,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,9,Madan,Mohan,Senior General Manager,None,L7,26-01-1961 00:00,14-01-2016 00:00,1008 Vrinda Ave MT,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,madan.mohan@chinookcorp.com

In [13]:
## Q2 Countries With Most Invoices 
query = """
SELECT billing_country, COUNT(*) AS invoice_count
FROM invoices
GROUP BY billing_country
ORDER BY invoice_count DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\679992803.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   billing_country  invoice_count
0              USA            131
1           Canada             76
2           Brazil             61
3           France             50
4          Germany             41
5   Czech Republic             30
6         Portugal             29
7   United Kingdom             28
8            India             21
9            Chile             13
10         Ireland             13
11           Spain             11
12         Finland             11
13       Australia             10
14     Netherlands             10
15          Sweden             10
16          Poland             10
17         Hungary             10
18         Denmark             10
19         Austria              9
20          Norway              9
21           Italy              9
22         Belgium              7
23       Argentina              5

In [14]:
## Q3 Top 3 Invoice Totals 
query = """
SELECT total
FROM invoices
ORDER BY total DESC
LIMIT 3;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\1647488873.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   total
0  23.76
1  19.80
2  19.80

In [15]:
## Q4 City With Best Customers
query = """
SELECT billing_city, SUM(total) AS total_revenue
FROM invoices
GROUP BY billing_city
ORDER BY total_revenue DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\564635705.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

  billing_city  total_revenue
0       Prague         273.24

In [16]:
## Q5 Best Customer
query = """
SELECT c.customer_id,
       c.first_name,
       c.last_name,
       SUM(i.total) AS total_spent
FROM customers c
JOIN invoices i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\2169346181.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   customer_id first_name    last_name  total_spent
0            5  František  Wichterlová       144.54

In [17]:
## Q6 Rock Music Listeners 
query = """
SELECT DISTINCT c.email,
       c.first_name,
       c.last_name,
       g.name AS genre
FROM customers c
JOIN invoices i
ON c.customer_id = i.customer_id
JOIN invoice_items ii
ON i.invoice_id = ii.invoice_id
JOIN tracks t
ON ii.track_id = t.track_id
JOIN genres g
ON t.genre_id = g.genre_id
WHERE g.name = 'Rock'
ORDER BY c.email;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\3028414686.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                            email first_name     last_name genre
0          aaronmitchell@yahoo.ca      Aaron      Mitchell  Rock
1                alero@uol.com.br  Alexandre         Rocha  Rock
2          astrid.gruber@apple.at     Astrid        Gruber  Rock
3           bjorn.hansen@yahoo.no      Bjørn        Hansen  Rock
4        camille.bernard@yahoo.fr    Camille       Bernard  Rock
5           daan_peeters@apple.be       Daan       Peeters  Rock
6        diego.gutierrez@yahoo.ar      Diego     Gutiérrez  Rock
7             dmiller@comcast.com        Dan        Miller  Rock
8     dominiquelefebvre@gmail.com  Dominique      Lefebvre  Rock
9             edfrancis@yachoo.ca     Edward       Francis  Rock
10       eduardo@woodstock.com.br    Eduardo       Martins  Rock
11         ellie.sullivan@shaw.ca      Ellie      Sullivan  Rock
12         emma_jones@hotmail.com       Emma         Jones  Rock
13         enrique_munoz@yahoo.es    Enrique         Muñoz  Rock
14       fernadaramos4@uol.com.br   Fernanda         Ramos  Rock
15             fharris@google.com      Frank        Harris  Rock
16             fralston@gmail.com      Frank       Ralston  Rock
17       frantisekw@jetbrains.com  František   Wichterlová  Rock
18            ftremblay@gmail.com   François      Tremblay  Rock
19           fzimmermann@yahoo.de       Fynn    Zimmermann  Rock
20      hannah.schneider@yahoo.de     Hannah     Schneider  Rock
21                hholy@gmail.com     Helena          Holý  Rock
22             hleacock@gmail.com    Heather       Leacock  Rock
23           hughoreilly@apple.ie       Hugh      O'Reilly  Rock
24      isabelle_mercier@apple.fr   Isabelle       Mercier  Rock
25        jacksmith@microsoft.com       Jack         Smith  Rock
26            jenniferp@rogers.ca   Jennifer      Peterson  Rock
27            jfernandes@yahoo.pt       João     Fernandes  Rock
28      joakim.johansson@yahoo.se     Joakim     Johansson  Rock
29        johavanderberg@yahoo.nl   Johannes  Van der Berg  Rock
30         johngordon22@yahoo.com       John        Gordon  Rock
31            jubarnett@gmail.com      Julia       Barnett  Rock
32            kachase@hotmail.com      Kathy         Chase  Rock
33          kara.nielsen@jubii.dk       Kara       Nielsen  Rock
34       ladislav_kovacs@apple.hu   Ladislav        Kovács  Rock
35          leonekohler@surfeu.de     Leonie        Köhler  Rock
36         lucas.mancini@yahoo.it      Lucas       Mancini  Rock
37           luisg@embraer.com.br       Luís     Gonçalves  Rock
38             luisrojas@yahoo.cl       Luis         Rojas  Rock
39        manoj.pareek@rediff.com      Manoj        Pareek  Rock
40        marc.dubois@hotmail.com       Marc        Dubois  Rock
41           mark.taylor@yahoo.au       Mark        Taylor  Rock
42           marthasilk@gmail.com     Martha          Silk  Rock
43              masampaio@sapo.pt   Madalena       Sampaio  Rock
44              michelleb@aol.com   Michelle        Brooks  Rock
45             mphilips12@shaw.ca       Mark       Philips  Rock
46            nschroder@surfeu.de     Niklas      Schröder  Rock
47           patrick.gray@aol.com    Patrick          Gray  Rock
48          phil.hughes@gmail.com       Phil        Hughes  Rock
49       ricunningham@hotmail.com    Richard    Cunningham  Rock
50        rishabh_mishra@yahoo.in    Rishabh        Mishra  Rock
51               robbrown@shaw.ca     Robert         Brown  Rock
52  roberto.almeida@riotur.gov.br    Roberto       Almeida  Rock
53         stanisław.wójcik@wp.pl  Stanisław        Wójcik  Rock
54          steve.murray@yahoo.uk      Steve        Murray  Rock
55      terhi.hamalainen@apple.fi      Terhi    Hämäläinen  Rock
56               tgoyer@apple.com        Tim         Goyer  Rock
57             vstevens@yahoo.com     Victor       Stevens  Rock
58          wyatt.girard@yahoo.fr      Wyatt        Girard  Rock

In [18]:
## Q7 Top 10 Rock Bands 
query = """
SELECT ar.name AS artist_name,
       COUNT(t.track_id) AS rock_track_count
FROM artists ar
JOIN albums al
ON ar.artist_id = al.artist_id
JOIN tracks t
ON al.album_id = t.album_id
JOIN genres g
ON t.genre_id = g.genre_id
WHERE g.name = 'Rock'
GROUP BY ar.name
ORDER BY rock_track_count DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\1265363803.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                    artist_name  rock_track_count
0                  Led Zeppelin               114
1                            U2               112
2                   Deep Purple                92
3                   Iron Maiden                81
4                     Pearl Jam                54
5                     Van Halen                52
6                         Queen                45
7            The Rolling Stones                41
8  Creedence Clearwater Revival                40
9                          Kiss                35

In [19]:
## Q8 Tracks Longer Than Average Length 
query = """
SELECT name, milliseconds
FROM tracks
WHERE milliseconds > (
        SELECT AVG(milliseconds)
        FROM tracks
)
ORDER BY milliseconds DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\2820463852.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                                                  name  milliseconds
0                               Occupation / Precipice       5286953
1                              Through a Looking Glass       5088838
2                          Greetings from Earth, Pt. 1       2960293
3                              The Man With Nine Lives       2956998
4                          Battlestar Galactica, Pt. 2       2956081
..                                                 ...           ...
489                                   22 Acacia Avenue        395572
490                                  The Unforgiven II        395520
491                                 The Shortest Straw        395389
492  Concerto for Clarinet in A Major, K. 622: II. ...        394482
493                                        Wicked Ways        393691

[494 rows x 2 columns]

In [20]:
## Q9 Amount Spent by Each Customer on Artists 
query = """
SELECT 
    c.first_name || ' ' || c.last_name AS customer_name,
    ar.name AS artist_name,
    SUM(ii.unit_price * ii.quantity) AS total_spent
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
JOIN invoice_items ii
    ON i.invoice_id = ii.invoice_id
JOIN tracks t
    ON ii.track_id = t.track_id
JOIN albums al
    ON t.album_id = al.album_id
JOIN artists ar
    ON al.artist_id = ar.artist_id
GROUP BY customer_name, ar.name
ORDER BY total_spent DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\3550722242.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           customer_name                   artist_name  total_spent
0          Hugh O'Reilly                         Queen        27.72
1           Wyatt Girard                 Frank Sinatra        23.76
2            Helena Holý         Red Hot Chili Peppers        19.80
3           Robert Brown  Creedence Clearwater Revival        19.80
4      François Tremblay                       The Who        19.80
...                  ...                           ...          ...
2184    Joakim Johansson                 Faith No More         0.99
2185  Richard Cunningham                Caetano Veloso         0.99
2186      Ellie Sullivan                    Audioslave         0.99
2187    Stanisław Wójcik                   Deep Purple         0.99
2188      Aaron Mitchell                    Pink Floyd         0.99

[2189 rows x 3 columns]

In [21]:
## Q10 Most Popular Genre for Each Country 
query = """
WITH genre_purchases AS (
    SELECT 
        c.country,
        g.name AS genre,
        COUNT(ii.quantity) AS purchases
    FROM customers c
    JOIN invoices i 
        ON c.customer_id = i.customer_id
    JOIN invoice_items ii 
        ON i.invoice_id = ii.invoice_id
    JOIN tracks t 
        ON ii.track_id = t.track_id
    JOIN genres g 
        ON t.genre_id = g.genre_id
    GROUP BY c.country, g.name
),
ranked_genres AS (
    SELECT *,
           RANK() OVER(PARTITION BY country ORDER BY purchases DESC) AS rank
    FROM genre_purchases
)
SELECT country, genre, purchases
FROM ranked_genres
WHERE rank = 1
ORDER BY country;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\315478751.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country               genre  purchases
0        Argentina  Alternative & Punk         17
1        Australia                Rock         34
2          Austria                Rock         40
3          Belgium                Rock         26
4           Brazil                Rock        205
5           Canada                Rock        333
6            Chile                Rock         61
7   Czech Republic                Rock        143
8          Denmark                Rock         24
9          Finland                Rock         46
10          France                Rock        211
11         Germany                Rock        194
12         Hungary                Rock         44
13           India                Rock        102
14         Ireland                Rock         72
15           Italy                Rock         35
16     Netherlands                Rock         33
17          Norway                Rock         40
18          Poland                Rock         40
19        Portugal                Rock        108
20           Spain                Rock         46
21          Sweden                Rock         60
22  United Kingdom                Rock        166
23             USA                Rock        561

In [22]:
## Q11 Top Customer in Each Country 
query = """
WITH customer_spending AS (
    SELECT 
        c.country,
        c.first_name || ' ' || c.last_name AS customer_name,
        SUM(i.total) AS total_spent
    FROM customers c
    JOIN invoices i
        ON c.customer_id = i.customer_id
    GROUP BY c.country, customer_name
),
ranked_customers AS (
    SELECT *,
           RANK() OVER(PARTITION BY country ORDER BY total_spent DESC) AS rank
    FROM customer_spending
)
SELECT country, customer_name, total_spent
FROM ranked_customers
WHERE rank = 1
ORDER BY country;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\2378870555.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country          customer_name  total_spent
0        Argentina        Diego Gutiérrez        39.60
1        Australia            Mark Taylor        81.18
2          Austria          Astrid Gruber        69.30
3          Belgium           Daan Peeters        60.39
4           Brazil         Luís Gonçalves       108.90
5           Canada      François Tremblay        99.99
6            Chile             Luis Rojas        97.02
7   Czech Republic  František Wichterlová       144.54
8          Denmark           Kara Nielsen        37.62
9          Finland       Terhi Hämäläinen        79.20
10          France           Wyatt Girard        99.99
11         Germany        Fynn Zimmermann        94.05
12         Hungary        Ladislav Kovács        78.21
13           India           Manoj Pareek       111.87
14         Ireland          Hugh O'Reilly       114.84
15           Italy          Lucas Mancini        50.49
16     Netherlands  Johannes Van der Berg        65.34
17          Norway           Bjørn Hansen        72.27
18          Poland       Stanisław Wójcik        76.23
19        Portugal         João Fernandes       102.96
20           Spain          Enrique Muñoz        98.01
21          Sweden       Joakim Johansson        75.24
22  United Kingdom            Phil Hughes        98.01
23             USA             Jack Smith        98.01

In [23]:
## Q12 Most Popular Artists 
query = """
SELECT 
    ar.name AS artist_name,
    COUNT(ii.quantity) AS total_purchases
FROM artists ar
JOIN albums al
    ON ar.artist_id = al.artist_id
JOIN tracks t
    ON al.album_id = t.album_id
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY ar.name
ORDER BY total_purchases DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\817670515.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

             artist_name  total_purchases
0                  Queen              192
1           Jimi Hendrix              187
2                Nirvana              130
3  Red Hot Chili Peppers              130
4              Pearl Jam              129
5          Guns N' Roses              124
6                  AC/DC              124
7           Foo Fighters              121
8     The Rolling Stones              117
9              Metallica              106

In [24]:
## Q13 Most Popular Song 
query = """
SELECT 
    t.name AS track_name,
    COUNT(ii.quantity) AS purchase_count
FROM tracks t
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY t.name
ORDER BY purchase_count DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\2412863268.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

  track_name  purchase_count
0   War Pigs              33

In [25]:
## Q14 Average Price by Media Type 
query = """
SELECT 
    m.name AS media_type,
    AVG(t.unit_price) AS average_price
FROM tracks t
JOIN media_types m
    ON t.media_type_id = m.media_type_id
GROUP BY m.name
ORDER BY average_price DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\1618049690.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                    media_type  average_price
0  Protected MPEG-4 video file       1.985327
1     Protected AAC audio file       0.990000
2               AAC audio file       0.990000
3     Purchased AAC audio file       0.990000
4              MPEG audio file       0.990000

In [26]:
## Q15 Most Popular Countries for Music Purchases 
query = """
SELECT 
    c.country,
    COUNT(ii.invoice_line_id) AS total_purchases
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
JOIN invoice_items ii
    ON i.invoice_id = ii.invoice_id
GROUP BY c.country
ORDER BY total_purchases DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_8388\3824280096.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country  total_purchases
0              USA             1051
1           Canada              541
2           Brazil              432
3           France              393
4          Germany              338
5   Czech Republic              276
6   United Kingdom              248
7         Portugal              187
8            India              185
9          Ireland              116
10           Spain               99
11           Chile               98
12       Australia               82
13         Finland               80
14         Hungary               79
15          Poland               77
16          Sweden               76
17          Norway               73
18         Austria               70
19     Netherlands               66
20         Belgium               61
21           Italy               51
22       Argentina               40
23         Denmark               38

In [7]:
###Business Questions

In [6]:
## Section 1 — Customer Analytics

In [5]:
## Customer Analytics - Top Spending Customers 
query = """
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.country,
    SUM(i.total) AS total_spent
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY c.customer_id, customer_name, c.country
ORDER BY total_spent DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\967909286.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   customer_id          customer_name         country  total_spent
0            5  František Wichterlová  Czech Republic       144.54
1            6            Helena Holý  Czech Republic       128.70
2           46          Hugh O'Reilly         Ireland       114.84
3           58           Manoj Pareek           India       111.87
4            1         Luís Gonçalves          Brazil       108.90
5           13         Fernanda Ramos          Brazil       106.92
6           34         João Fernandes        Portugal       102.96
7            3      François Tremblay          Canada        99.99
8           42           Wyatt Girard          France        99.99
9           17             Jack Smith             USA        98.01

In [8]:
## Average Customer Lifetime Value 
query = """
SELECT 
    AVG(customer_total) AS avg_customer_lifetime_value
FROM (
    SELECT 
        customer_id,
        SUM(total) AS customer_total
    FROM invoices
    GROUP BY customer_id
) sub;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3116901814.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   avg_customer_lifetime_value
0                    79.820847

In [9]:
## Repeat vs One-Time Customers 
query = """
SELECT 
CASE 
    WHEN purchase_count = 1 THEN 'One-Time Buyer'
    ELSE 'Repeat Customer'
END AS customer_type,
COUNT(*) AS total_customers
FROM (
    SELECT 
        customer_id,
        COUNT(invoice_id) AS purchase_count
    FROM invoices
    GROUP BY customer_id
) sub
GROUP BY customer_type;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1263344113.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

     customer_type  total_customers
0  Repeat Customer               59

In [10]:
## Revenue Per Customer by Country 
query = """
SELECT 
    c.country,
    SUM(i.total)/COUNT(DISTINCT c.customer_id) AS revenue_per_customer
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY c.country
ORDER BY revenue_per_customer DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1247585386.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country  revenue_per_customer
0   Czech Republic            136.620000
1          Ireland            114.840000
2            Spain             98.010000
3            Chile             97.020000
4         Portugal             92.565000
5            India             91.575000
6           Brazil             85.536000
7          Germany             83.655000
8   United Kingdom             81.840000
9        Australia             81.180000
10             USA             80.037692
11         Finland             79.200000
12         Hungary             78.210000
13          France             77.814000
14          Poland             76.230000
15          Sweden             75.240000
16          Norway             72.270000
17         Austria             69.300000
18          Canada             66.948750
19     Netherlands             65.340000
20         Belgium             60.390000
21           Italy             50.490000
22       Argentina             39.600000
23         Denmark             37.620000

In [12]:
## Inactive Customers (Last 6 Months) 
query = """
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    MAX(i.invoice_date::DATE) AS last_purchase
FROM customers c
LEFT JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY c.customer_id, customer_name
HAVING MAX(i.invoice_date::DATE) < (
    SELECT MAX(invoice_date::DATE) - INTERVAL '6 months'
    FROM invoices
);
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3715230082.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    customer_id          customer_name last_purchase
0            10        Eduardo Martins    2020-06-25
1            43       Isabelle Mercier    2020-05-02
2            18        Michelle Brooks    2020-03-05
3            48  Johannes Van der Berg    2020-04-27
4            50          Enrique Muñoz    2020-06-10
5             8           Daan Peeters    2019-09-21
6            19              Tim Goyer    2020-04-14
7            36       Hannah Schneider    2020-04-07
8            57             Luis Rojas    2020-06-09
9            38        Niklas Schröder    2020-04-22
10            9           Kara Nielsen    2020-01-29
11           11        Alexandre Rocha    2020-06-24
12           54           Steve Murray    2020-03-25
13            4           Bjørn Hansen    2020-02-04
14            3      François Tremblay    2020-05-16
15           39        Camille Bernard    2020-04-11

In [14]:
## Section 2 — Sales & Revenue Analysis

In [15]:
## Sales Analysis - Monthly Revenue Trends 
query = """
SELECT 
    DATE_TRUNC('month', invoice_date::DATE) AS month,
    SUM(total) AS monthly_revenue
FROM invoices
WHERE invoice_date::DATE >= (
    SELECT MAX(invoice_date::DATE) - INTERVAL '2 years'
    FROM invoices
)
GROUP BY month
ORDER BY month;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2666228549.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                       month  monthly_revenue
0  2018-12-31 18:30:00+00:00            85.14
1  2019-01-31 18:30:00+00:00            59.40
2  2019-02-28 18:30:00+00:00           125.73
3  2019-03-31 18:30:00+00:00           116.82
4  2019-04-30 18:30:00+00:00           104.94
5  2019-05-31 18:30:00+00:00            92.07
6  2019-06-30 18:30:00+00:00           124.74
7  2019-07-31 18:30:00+00:00           159.39
8  2019-08-31 18:30:00+00:00           126.72
9  2019-09-30 18:30:00+00:00            43.56
10 2019-10-31 18:30:00+00:00            71.28
11 2019-11-30 18:30:00+00:00           111.87
12 2019-12-31 18:30:00+00:00            43.56
13 2020-01-31 18:30:00+00:00            97.02
14 2020-02-29 18:30:00+00:00            78.21
15 2020-03-31 18:30:00+00:00           119.79
16 2020-04-30 18:30:00+00:00            82.17
17 2020-05-31 18:30:00+00:00           120.78
18 2020-06-30 18:30:00+00:00            76.23
19 2020-07-31 18:30:00+00:00            72.27
20 2020-08-31 18:30:00+00:00            95.04
21 2020-09-30 18:30:00+00:00           144.54
22 2020-10-31 18:30:00+00:00            83.16
23 2020-11-30 18:30:00+00:00           125.73

In [16]:
# # What is the average value of an invoice (purchase)?
query = """
SELECT 
    AVG(total) AS average_invoice_value
FROM invoices;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2190012419.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   average_invoice_value
0               7.670081

In [17]:
## Which payment methods are used most frequently? 
query = """
SELECT 
    billing_country,
    COUNT(invoice_id) AS total_transactions
FROM invoices
GROUP BY billing_country
ORDER BY total_transactions DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2581322495.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   billing_country  total_transactions
0              USA                 131
1           Canada                  76
2           Brazil                  61
3           France                  50
4          Germany                  41
5   Czech Republic                  30
6         Portugal                  29
7   United Kingdom                  28
8            India                  21
9            Chile                  13
10         Ireland                  13
11           Spain                  11
12         Finland                  11
13       Australia                  10
14     Netherlands                  10
15          Sweden                  10
16          Poland                  10
17         Hungary                  10
18         Denmark                  10
19         Austria                   9
20          Norway                   9
21           Italy                   9
22         Belgium                   7
23       Argentina                   5

In [18]:
## How much revenue does each sales representative contribute? 
query = """
SELECT 
    e.employee_id,
    e.first_name || ' ' || e.last_name AS sales_rep,
    SUM(i.total) AS total_revenue
FROM employees e
JOIN customers c
    ON e.employee_id = c.support_rep_id
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY e.employee_id, sales_rep
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1630588305.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   employee_id      sales_rep  total_revenue
0            3   Jane Peacock        1731.51
1            4  Margaret Park        1584.00
2            5  Steve Johnson        1393.92

In [19]:
### Which months or quarters have peak music sales? 
query = """
SELECT 
    DATE_TRUNC('month', invoice_date::DATE) AS month,
    SUM(total) AS total_revenue
FROM invoices
GROUP BY month
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2886600747.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                       month  total_revenue
0  2017-12-31 18:30:00+00:00         183.15
1  2019-07-31 18:30:00+00:00         159.39
2  2018-02-28 18:30:00+00:00         148.50
3  2020-09-30 18:30:00+00:00         144.54
4  2017-03-31 18:30:00+00:00         142.56
5  2017-01-31 18:30:00+00:00         141.57
6  2019-08-31 18:30:00+00:00         126.72
7  2016-12-31 18:30:00+00:00         126.72
8  2020-11-30 18:30:00+00:00         125.73
9  2019-02-28 18:30:00+00:00         125.73
10 2019-06-30 18:30:00+00:00         124.74
11 2020-05-31 18:30:00+00:00         120.78
12 2020-03-31 18:30:00+00:00         119.79
13 2018-01-31 18:30:00+00:00         116.82
14 2019-03-31 18:30:00+00:00         116.82
15 2019-11-30 18:30:00+00:00         111.87
16 2017-06-30 18:30:00+00:00         108.90
17 2017-08-31 18:30:00+00:00         107.91
18 2018-07-31 18:30:00+00:00         106.92
19 2017-04-30 18:30:00+00:00         104.94
20 2019-04-30 18:30:00+00:00         104.94
21 2017-02-28 18:30:00+00:00         103.95
22 2018-11-30 18:30:00+00:00          98.01
23 2020-01-31 18:30:00+00:00          97.02
24 2020-08-31 18:30:00+00:00          95.04
25 2017-10-31 18:30:00+00:00          94.05
26 2019-05-31 18:30:00+00:00          92.07
27 2018-05-31 18:30:00+00:00          92.07
28 2017-07-31 18:30:00+00:00          88.11
29 2018-12-31 18:30:00+00:00          85.14
30 2018-06-30 18:30:00+00:00          85.14
31 2020-10-31 18:30:00+00:00          83.16
32 2020-04-30 18:30:00+00:00          82.17
33 2017-09-30 18:30:00+00:00          79.20
34 2018-09-30 18:30:00+00:00          78.21
35 2020-02-29 18:30:00+00:00          78.21
36 2018-04-30 18:30:00+00:00          76.23
37 2020-06-30 18:30:00+00:00          76.23
38 2017-05-31 18:30:00+00:00          75.24
39 2020-07-31 18:30:00+00:00          72.27
40 2019-10-31 18:30:00+00:00          71.28
41 2018-03-31 18:30:00+00:00          63.36
42 2019-01-31 18:30:00+00:00          59.40
43 2018-08-31 18:30:00+00:00          56.43
44 2019-09-30 18:30:00+00:00          43.56
45 2019-12-31 18:30:00+00:00          43.56
46 2018-10-31 18:30:00+00:00          42.57
47 2017-11-30 18:30:00+00:00          28.71

In [20]:
## Section 3 — Product & Content Analysis

In [21]:
## Top Revenue Generating Tracks 
query = """
SELECT 
    t.track_id,
    t.name AS track_name,
    SUM(ii.unit_price * ii.quantity) AS total_revenue
FROM tracks t
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY t.track_id, t.name
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\124636665.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   track_id                track_name  total_revenue
0      3336                  War Pigs          30.69
1      1495             Highway Chile          13.86
2      1489      Are You Experienced?          13.86
3      1490                   Hey Joe          12.87
4      1487  Third Stone From The Sun          12.87
5         6     Put The Finger On You          12.87
6      1483         Love Or Confusion          11.88
7      2558               Radio/Video          11.88
8      1493          51st Anniversary          10.89
9      1129           Dead And Broken          10.89

In [22]:
## Which albums or playlists are most frequently included in purchases?  
query = """
SELECT 
    al.album_id,
    al.title AS album_name,
    COUNT(ii.invoice_line_id) AS purchase_count
FROM albums al
JOIN tracks t
    ON al.album_id = t.album_id
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY al.album_id, album_name
ORDER BY purchase_count DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1204807848.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   album_id                                  album_name  purchase_count
0       120                        Are You Experienced?             187
1        88                                    Faceless              96
2       207                                   Mezmerize              93
3       119                                    Get Born              90
4       214                                   The Doors              83
5       215                    The Police Greatest Hits              80
6       185                             Greatest Hits I              80
7         5                                    Big Ones              80
8       163  From The Muddy Banks Of The Wishkah [live]              78
9       221    My Generation - The Very Best Of The Who              76

In [23]:
## Tracks Never Purchased
query = """
SELECT 
    t.track_id,
    t.name AS track_name
FROM tracks t
LEFT JOIN invoice_items ii
    ON t.track_id = ii.track_id
WHERE ii.invoice_line_id IS NULL;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2798396037.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

      track_id                 track_name
0         2848             Six Months Ago
1          251  Um Passeio No Mundo Livre
2         2026                   Às Vezes
3         3028                    Zooropa
4         2024                       Deus
...        ...                        ...
1692      2460               Preto Damião
1693      2283                Me In Honey
1694      1709             American Woman
1695      2502       The Everlasting Gaze
1696      2824                       Torn

[1697 rows x 2 columns]

In [24]:
## Average Track Price by Genre 
query = """
SELECT 
    g.genre_id,
    g.name AS genre_name,
    AVG(t.unit_price) AS avg_track_price
FROM genres g
JOIN tracks t
    ON g.genre_id = t.genre_id
GROUP BY g.genre_id, genre_name
ORDER BY avg_track_price DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1842014633.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    genre_id          genre_name  avg_track_price
0         19            TV Shows             1.99
1         20    Sci Fi & Fantasy             1.99
2         18     Science Fiction             1.99
3         22              Comedy             1.99
4         21               Drama             1.99
5          1                Rock             0.99
6          7               Latin             0.99
7          3               Metal             0.99
8          4  Alternative & Punk             0.99
9         14            R&B/Soul             0.99
10         8              Reggae             0.99
11         9                 Pop             0.99
12        11          Bossa Nova             0.99
13         5       Rock And Roll             0.99
14        25               Opera             0.99
15        10          Soundtrack             0.99
16        23         Alternative             0.99
17        24           Classical             0.99
18        12      Easy Listening             0.99
19        17         Hip Hop/Rap             0.99
20        15   Electronica/Dance             0.99
21         6               Blues             0.99
22        16               World             0.99
23        13         Heavy Metal             0.99
24         2                Jazz             0.99

In [25]:
## Track Count vs Sales by Genre 
query = """
SELECT 
    g.genre_id,
    g.name AS genre_name,
    COUNT(DISTINCT t.track_id) AS total_tracks,
    COUNT(ii.invoice_line_id) AS total_sales
FROM genres g
LEFT JOIN tracks t
    ON g.genre_id = t.genre_id
LEFT JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY g.genre_id, genre_name
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\4248856505.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    genre_id          genre_name  total_tracks  total_sales
0          1                Rock          1297         2635
1          3               Metal           374          619
2          4  Alternative & Punk           332          492
3          7               Latin           579          167
4         14            R&B/Soul            61          159
5          6               Blues            81          124
6          2                Jazz           130          121
7         23         Alternative            40          117
8         12      Easy Listening            24           74
9          9                 Pop            48           63
10        15   Electronica/Dance            30           55
11        24           Classical            74           47
12         8              Reggae            58           35
13        17         Hip Hop/Rap            35           33
14        13         Heavy Metal            28            8
15        10          Soundtrack            43            5
16        19            TV Shows            93            2
17        21               Drama            64            1
18        20    Sci Fi & Fantasy            26            0
19        22              Comedy            17            0
20         5       Rock And Roll            12            0
21        16               World            28            0
22        25               Opera             1            0
23        11          Bossa Nova            15            0
24        18     Science Fiction            13            0

In [26]:
## Section 4 — Artist & Genre Performance

In [27]:
## Top 5 Highest Grossing Artists 
query = """
SELECT 
    ar.artist_id,
    ar.name AS artist_name,
    SUM(ii.unit_price * ii.quantity) AS total_revenue
FROM artists ar
JOIN albums al
    ON ar.artist_id = al.artist_id
JOIN tracks t
    ON al.album_id = t.album_id
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY ar.artist_id, artist_name
ORDER BY total_revenue DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3594874980.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   artist_id            artist_name  total_revenue
0         51                  Queen         190.08
1         94           Jimi Hendrix         185.13
2        110                Nirvana         128.70
3        127  Red Hot Chili Peppers         128.70
4        118              Pearl Jam         127.71

In [28]:
## Genre Popularity by Sales and Revenue 
query = """
SELECT 
    g.genre_id,
    g.name AS genre_name,
    COUNT(ii.invoice_line_id) AS tracks_sold,
    SUM(ii.unit_price * ii.quantity) AS total_revenue
FROM genres g
JOIN tracks t
    ON g.genre_id = t.genre_id
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY g.genre_id, genre_name
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2072515329.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    genre_id          genre_name  tracks_sold  total_revenue
0          1                Rock         2635        2608.65
1          3               Metal          619         612.81
2          4  Alternative & Punk          492         487.08
3          7               Latin          167         165.33
4         14            R&B/Soul          159         157.41
5          6               Blues          124         122.76
6          2                Jazz          121         119.79
7         23         Alternative          117         115.83
8         12      Easy Listening           74          73.26
9          9                 Pop           63          62.37
10        15   Electronica/Dance           55          54.45
11        24           Classical           47          46.53
12         8              Reggae           35          34.65
13        17         Hip Hop/Rap           33          32.67
14        13         Heavy Metal            8           7.92
15        10          Soundtrack            5           4.95
16        19            TV Shows            2           1.98
17        21               Drama            1           0.99

In [29]:
## Genre Popularity by Country 
query = """
SELECT 
    c.country,
    g.name AS genre_name,
    COUNT(ii.invoice_line_id) AS total_purchases
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
JOIN invoice_items ii
    ON i.invoice_id = ii.invoice_id
JOIN tracks t
    ON ii.track_id = t.track_id
JOIN genres g
    ON t.genre_id = g.genre_id
GROUP BY c.country, genre_name
ORDER BY c.country, total_purchases DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1665708293.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

       country          genre_name  total_purchases
0    Argentina  Alternative & Punk               17
1    Argentina                Rock               11
2    Argentina               Metal                2
3    Argentina               Blues                2
4    Argentina               Latin                2
..         ...                 ...              ...
269        USA   Electronica/Dance                5
270        USA           Classical                4
271        USA         Heavy Metal                3
272        USA          Soundtrack                2
273        USA            TV Shows                1

[274 rows x 3 columns]

In [30]:
## Section 5 — Employee & Operational Efficiency

In [31]:
## Employees Managing Highest-Spending Customers 
query = """
SELECT 
    e.employee_id,
    e.first_name || ' ' || e.last_name AS employee_name,
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    SUM(i.total) AS customer_total_spent
FROM employees e
JOIN customers c
    ON e.employee_id = c.support_rep_id
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY e.employee_id, employee_name, c.customer_id, customer_name
ORDER BY customer_total_spent DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3056754851.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

,employee_id,employee_name,customer_id,customer_name,customer_total_spent
0,4,Margaret Park,5,František Wichterlová,144.54
1,5,Steve Johnson,6,Helena Holý,128.70
2,3,Jane Peacock,46,Hugh O'Reilly,114.84
3,3,Jane Peacock,58,Manoj Pareek,111.87
4,3,Jane Peacock,1,Luís Gonçalves,108.90
5,4,Margaret Park,13,Fernanda Ramos,106.92
6,4,Margaret Park,34,João Fernandes,102.96
7,3,Jane Peacock,42,Wyatt Girard,99.99
8,3,Jane Peacock,3,François Tremblay,99.99
9,5,Steve Johnson,17,Jack Smith,98.01

In [32]:
## Average Number of Customers per Employee 
query = """
SELECT 
    AVG(customer_count) AS avg_customers_per_employee
FROM (
    SELECT 
        support_rep_id,
        COUNT(customer_id) AS customer_count
    FROM customers
    GROUP BY support_rep_id
) sub;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\2296601320.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   avg_customers_per_employee
0                   19.666667

In [33]:
## Revenue by Employee Region 
query = """
SELECT 
    e.employee_id,
    e.first_name || ' ' || e.last_name AS employee_name,
    c.country AS customer_region,
    SUM(i.total) AS total_revenue
FROM employees e
JOIN customers c
    ON e.employee_id = c.support_rep_id
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY e.employee_id, employee_name, customer_region
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\4209764645.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    employee_id  employee_name customer_region  total_revenue
0             4  Margaret Park             USA         497.97
1             3   Jane Peacock          Canada         373.23
2             5  Steve Johnson             USA         337.59
3             3   Jane Peacock             USA         204.93
4             3   Jane Peacock          Brazil         191.07
5             4  Margaret Park        Portugal         185.13
6             3   Jane Peacock           India         183.15
7             3   Jane Peacock          France         173.25
8             3   Jane Peacock         Germany         167.31
9             4  Margaret Park          Brazil         167.31
10            5  Steve Johnson         Germany         167.31
11            3   Jane Peacock  United Kingdom         166.32
12            4  Margaret Park          France         151.47
13            4  Margaret Park  Czech Republic         144.54
14            5  Steve Johnson  Czech Republic         128.70
15            3   Jane Peacock         Ireland         114.84
16            5  Steve Johnson           Spain          98.01
17            5  Steve Johnson           Chile          97.02
18            5  Steve Johnson          Canada          92.07
19            4  Margaret Park       Australia          81.18
20            3   Jane Peacock         Finland          79.20
21            5  Steve Johnson  United Kingdom          79.20
22            3   Jane Peacock         Hungary          78.21
23            4  Margaret Park          Poland          76.23
24            5  Steve Johnson          Sweden          75.24
25            4  Margaret Park          Norway          72.27
26            4  Margaret Park          Canada          70.29
27            5  Steve Johnson          Brazil          69.30
28            5  Steve Johnson         Austria          69.30
29            5  Steve Johnson     Netherlands          65.34
30            5  Steve Johnson          France          64.35
31            4  Margaret Park         Belgium          60.39
32            5  Steve Johnson           Italy          50.49
33            4  Margaret Park       Argentina          39.60
34            4  Margaret Park         Denmark          37.62

In [34]:
## Section 6 — Geographic Trends

In [36]:
## Customer Distribution by Country

In [35]:
query = """
SELECT 
    country,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3994808009.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country  total_customers
0              USA               13
1           Canada                8
2           France                5
3           Brazil                5
4          Germany                4
5   United Kingdom                3
6         Portugal                2
7            India                2
8   Czech Republic                2
9           Norway                1
10          Sweden                1
11           Chile                1
12         Belgium                1
13     Netherlands                1
14         Hungary                1
15         Austria                1
16       Australia                1
17          Poland                1
18         Ireland                1
19           Italy                1
20         Denmark                1
21           Spain                1
22         Finland                1
23       Argentina                1

In [37]:
## Revenue by Country 
query = """
SELECT 
    c.country,
    SUM(i.total) AS total_revenue
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY c.country
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3958681255.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country  total_revenue
0              USA        1040.49
1           Canada         535.59
2           Brazil         427.68
3           France         389.07
4          Germany         334.62
5   Czech Republic         273.24
6   United Kingdom         245.52
7         Portugal         185.13
8            India         183.15
9          Ireland         114.84
10           Spain          98.01
11           Chile          97.02
12       Australia          81.18
13         Finland          79.20
14         Hungary          78.21
15          Poland          76.23
16          Sweden          75.24
17          Norway          72.27
18         Austria          69.30
19     Netherlands          65.34
20         Belgium          60.39
21           Italy          50.49
22       Argentina          39.60
23         Denmark          37.62

In [38]:
## Underserved Geographic Regions 
query = """
SELECT 
    c.country,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    SUM(i.total) AS total_revenue,
    SUM(i.total) / COUNT(DISTINCT c.customer_id) AS revenue_per_customer
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY c.country
ORDER BY revenue_per_customer ASC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3932318165.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

           country  total_customers  total_revenue  revenue_per_customer
0          Denmark                1          37.62             37.620000
1        Argentina                1          39.60             39.600000
2            Italy                1          50.49             50.490000
3          Belgium                1          60.39             60.390000
4      Netherlands                1          65.34             65.340000
5           Canada                8         535.59             66.948750
6          Austria                1          69.30             69.300000
7           Norway                1          72.27             72.270000
8           Sweden                1          75.24             75.240000
9           Poland                1          76.23             76.230000
10          France                5         389.07             77.814000
11         Hungary                1          78.21             78.210000
12         Finland                1          79.20             79.200000
13             USA               13        1040.49             80.037692
14       Australia                1          81.18             81.180000
15  United Kingdom                3         245.52             81.840000
16         Germany                4         334.62             83.655000
17          Brazil                5         427.68             85.536000
18           India                2         183.15             91.575000
19        Portugal                2         185.13             92.565000
20           Chile                1          97.02             97.020000
21           Spain                1          98.01             98.010000
22         Ireland                1         114.84            114.840000
23  Czech Republic                2         273.24            136.620000

In [39]:
## Section 7 — Customer Retention & Purchase Patterns.

In [40]:
## Purchase Frequency per Customer 
query = """
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(i.invoice_id) AS total_purchases
FROM customers c
JOIN invoices i
    ON c.customer_id = i.customer_id
GROUP BY c.customer_id, customer_name
ORDER BY total_purchases DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3400634840.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    customer_id          customer_name  total_purchases
0             5  František Wichterlová               18
1            35       Madalena Sampaio               16
2            13         Fernanda Ramos               15
3             1         Luís Gonçalves               13
4            46          Hugh O'Reilly               13
5            34         João Fernandes               13
6            58           Manoj Pareek               13
7            57             Luis Rojas               13
8            30         Edward Francis               13
9            33         Ellie Sullivan               12
10           43       Isabelle Mercier               12
11           26     Richard Cunningham               12
12            6            Helena Holý               12
13           22        Heather Leacock               12
14           17             Jack Smith               12
15           10        Eduardo Martins               12
16           20             Dan Miller               12
17           21            Kathy Chase               11
18           42           Wyatt Girard               11
19           12        Roberto Almeida               11
20           53            Phil Hughes               11
21           50          Enrique Muñoz               11
22           31            Martha Silk               11
23           36       Hannah Schneider               11
24           44       Terhi Hämäläinen               11
25            2          Leonie Köhler               11
26           14           Mark Philips               10
27           48  Johannes Van der Berg               10
28           37        Fynn Zimmermann               10
29            9           Kara Nielsen               10
30           28          Julia Barnett               10
31           49       Stanisław Wójcik               10
32           45        Ladislav Kovács               10
33           23            John Gordon               10
34           25         Victor Stevens               10
35           11        Alexandre Rocha               10
36           55            Mark Taylor               10
37           51       Joakim Johansson               10
38           27           Patrick Gray                9
39           40     Dominique Lefebvre                9
40            4           Bjørn Hansen                9
41           15      Jennifer Peterson                9
42           19              Tim Goyer                9
43            3      François Tremblay                9
44            7          Astrid Gruber                9
45           54           Steve Murray                9
46           38        Niklas Schröder                9
47           47          Lucas Mancini                9
48           39        Camille Bernard                9
49           41            Marc Dubois                9
50           16           Frank Harris                8
51           52             Emma Jones                8
52           24          Frank Ralston                8
53           18        Michelle Brooks                8
54           59         Rishabh Mishra                8
55           32         Aaron Mitchell                8
56            8           Daan Peeters                7
57           56        Diego Gutiérrez                5
58           29           Robert Brown                4

In [41]:
## Average Time Between Customer Purchases 
query = """
SELECT 
    AVG(days_between) AS avg_days_between_purchases
FROM (
    SELECT 
        customer_id,
        invoice_date::DATE - 
        LAG(invoice_date::DATE) OVER (
            PARTITION BY customer_id 
            ORDER BY invoice_date::DATE
        ) AS days_between
    FROM invoices
) sub
WHERE days_between IS NOT NULL;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1824829558.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   avg_days_between_purchases
0                  132.279279

In [42]:
## Customers Buying Multiple Genres 
query = """
SELECT 
    ROUND(
        100.0 * COUNT(*) / (SELECT COUNT(*) FROM customers), 
        2
    ) AS percentage_multi_genre_customers
FROM (
    SELECT 
        c.customer_id
    FROM customers c
    JOIN invoices i
        ON c.customer_id = i.customer_id
    JOIN invoice_items ii
        ON i.invoice_id = ii.invoice_id
    JOIN tracks t
        ON ii.track_id = t.track_id
    GROUP BY c.customer_id
    HAVING COUNT(DISTINCT t.genre_id) > 1
) sub;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\503392138.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   percentage_multi_genre_customers
0                             100.0

In [43]:
## Section 8 — Operational Optimization.

In [44]:
## Most Common Track Combinations Purchased Together 
query = """
SELECT 
    t1.name AS track_1,
    t2.name AS track_2,
    COUNT(*) AS times_purchased_together
FROM invoice_items ii1
JOIN invoice_items ii2
    ON ii1.invoice_id = ii2.invoice_id
    AND ii1.track_id < ii2.track_id
JOIN tracks t1
    ON ii1.track_id = t1.track_id
JOIN tracks t2
    ON ii2.track_id = t2.track_id
GROUP BY track_1, track_2
ORDER BY times_purchased_together DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1740771368.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

              track_1                   track_2  times_purchased_together
0   Love Or Confusion        I Don't Live Today                         9
1           Foxy Lady  Third Stone From The Sun                         9
2    May This Be Love             Highway Chile                         9
3            Remember                Stone Free                         8
4    May This Be Love               Purple Haze                         8
5      Can You See Me  Third Stone From The Sun                         8
6      Can You See Me          May This Be Love                         8
7    May This Be Love                Stone Free                         8
8    Manic Depression               Purple Haze                         8
9  I Don't Live Today                Stone Free                         8

In [45]:
## Pricing Patterns vs Sales 
query = """
SELECT 
    t.unit_price,
    COUNT(ii.invoice_line_id) AS total_sales,
    SUM(ii.unit_price * ii.quantity) AS total_revenue
FROM tracks t
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY t.unit_price
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3481514860.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   unit_price  total_sales  total_revenue
0        0.99         4754        4706.46
1        1.99            3           2.97

In [46]:
## Media Type Usage Trends 
query = """
SELECT 
    m.name AS media_type,
    COUNT(ii.invoice_line_id) AS total_purchases
FROM media_types m
JOIN tracks t
    ON m.media_type_id = t.media_type_id
JOIN invoice_items ii
    ON t.track_id = ii.track_id
GROUP BY media_type
ORDER BY total_purchases DESC;
"""

pd.read_sql(query, conn)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\1951129696.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                    media_type  total_purchases
0              MPEG audio file             4259
1     Protected AAC audio file              439
2     Purchased AAC audio file               35
3               AAC audio file               21
4  Protected MPEG-4 video file                3

In [47]:
## First we need the data to visualize.

In [48]:
df = pd.read_sql(query, conn)
df.to_csv("top_customers.csv", index=False)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3786938813.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [49]:
## Dataset 1 — Revenue by Country  
query = """
SELECT 
    c.country,
    SUM(i.total) AS total_revenue
FROM customers c
JOIN invoices i
ON c.customer_id = i.customer_id
GROUP BY c.country
ORDER BY total_revenue DESC;
"""
df = pd.read_sql(query, conn)
df.to_csv("revenue_by_country.csv", index=False)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\56234334.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [50]:
## Dataset 2 — Genre Popularity 
query = """
SELECT 
    g.name AS genre,
    COUNT(ii.invoice_line_id) AS purchases
FROM genres g
JOIN tracks t ON g.genre_id = t.genre_id
JOIN invoice_items ii ON t.track_id = ii.track_id
GROUP BY genre
ORDER BY purchases DESC;
"""
df = pd.read_sql(query, conn)
df.to_csv("genre_popularity.csv", index=False)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\559576618.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [51]:
## Dataset 3 — Top Artists 
query = """
SELECT 
    ar.name AS artist,
    SUM(ii.unit_price * ii.quantity) AS revenue
FROM artists ar
JOIN albums al ON ar.artist_id = al.artist_id
JOIN tracks t ON al.album_id = t.album_id
JOIN invoice_items ii ON t.track_id = ii.track_id
GROUP BY artist
ORDER BY revenue DESC
LIMIT 10;
"""
df = pd.read_sql(query, conn)
df.to_csv("top_artists.csv", index=False)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\4204691458.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [52]:
## Dataset 4 — Monthly Revenue 
query = """
SELECT 
    DATE_TRUNC('month', invoice_date::date) AS month,
    SUM(total) AS revenue
FROM invoices
GROUP BY month
ORDER BY month;
"""
df = pd.read_sql(query, conn)
df.to_csv("monthly_revenue.csv", index=False)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3494236179.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [53]:
## Dataset 5 — Top Customers 
query = """
SELECT 
    c.first_name || ' ' || c.last_name AS customer,
    SUM(i.total) AS total_spent
FROM customers c
JOIN invoices i ON c.customer_id = i.customer_id
GROUP BY customer
ORDER BY total_spent DESC
LIMIT 10;
"""
df = pd.read_sql(query, conn)
df.to_csv("top_customers.csv", index=False)

C:\Users\Raksha Shetty\AppData\Local\Temp\ipykernel_27340\3016970203.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)